version: '3.6'

services:

  wordpress:
    image: wordpress
    hostname: ronitascrafts_com__wordpress
    restart: unless-stopped
    volumes:
      - 'wordpress:/var/www/html'

  mariadb:
    hostname: ronitascrafts_com__mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
      - 'mariadb:/var/lib/mysql'

networks:
  default:
    name: pi
    external: true

volumes:
  wordpress:
  mariadb:
