version: '3.6'

services:

  wordpress:
    image: wordpress
    hostname: ronitascrafts_com-wordpress
    restart: unless-stopped
    ports:
      - '8081:80'
    volumes:
      - 'wordpress:/var/www/html'

  mariadb:
    hostname: ronitascrafts_com-mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
      - 'db:/var/lib/mysql'

volumes:
  wordpress:
  db:

networks:
  default:
    name: pi
    external: true
