version: '3.6'

services:

  wordpress:
    image: wordpress
    hostname: ronitascrafts_com-wordpress
    restart: unless-stopped
    volumes:
      - './wordpress:/var/www/html'

  mariadb:
    hostname: ronitascrafts_com-mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
      - './mariadb:/var/lib/mysql'

networks:
  default:
    name: pi
    external: true
