version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - '8081:80'
    volumes:
      - 'wordpress:/var/www/html'

  mariadb:
    image: mariadb
    restart: unless-stopped
    volumes:
      - 'db:/var/lib/mysql'

volumes:
  wordpress:
  db:
